### ISSUE TITLE
Doc strings?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GeoInterfaceRFC.jl#2]
A problem with GeoInterface.jl is it doesn't really have doc strings describing what the interface does.

The GeoInterface.jl file could have some solid docs describing what the types are for and what the methods do. I would break it up into types.jl for types and interface.jl for the methods, as if they are documented they will get a lot longer.

**Comment by visr** [comment]
Agree that good docstrings will be important for users of the interface. For now we are first focused on getting the design right, but maybe initial docstrings might make the review simpler as well.

**Comment by rafaqz** [comment]
Yeah @yeesian sent me here for a look but its hard to understand the intent without some doc strings. But otherwise looks pretty clean.
